# Site settings
title: "0a: a thunk, a propositional variable, a \\n"
description: "May the *force* be with you. Let us embrace null-arity. There exists a more straightforward interpretation as well. "
baseurl: "" # the subpath of your site, e.g. /blog/
imageurl: "/assets/img/"
fromThePast: "/assets/past/"
url: "http://0a.io" # the base hostname & protocol for your site
identity: 0a.io
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title/
# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap
collections:
  days_of_yore:
    output: true
    permalink: /article/:path/
  word_of_the_day:
    output: false
  article_of_the_week:
    output: false
encoding: utf-8
