# Site settings
title: "0a: Archy Wilhes at your service."
email: "a@0a.io"
description: "Reality is a simulation, and the past does not exist. My name is . I write."
baseurl: "" # the subpath of your site, e.g. /blog/
imageurl: "/assets/img/"
fromThePast: "/assets/past/"
url: "http://0a.io" # the base hostname & protocol for your site
identity: 0a.io
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title/
# Build settings
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap
collections:
  days_of_yore:
    output: true
    permalink: /article/:path/
  word_of_the_day:
    output: false
  article_of_the_week:
    output: false
encoding: utf-8
